/*
 * Copyright 2018 Perforce Software.  All rights reserved.
 *
 * This file is part of Perforce - the FAST SCM System.
 */

# ifndef P4SCRIPT53DEFS_H
# define P4SCRIPT53DEFS_H

// clear ; nm -gC ../p4-bin/bin.linux26x86_64/g/libp4script.a | grep -P ' T lua.?_' | cut -d ' ' -f 3 | cut -d '(' -f 1
// clear ; nm -gC ../p4-bin/bin.linux26x86_64/g/libp4script.a | grep ' T '

#define Proto p4lua53_Proto
#define TMS p4lua53_TMS
#define TString p4lua53_TString
#define TValue p4lua53_TValue
#define Table p4lua53_Table
#define ZIO p4lua53_ZIO
#define dothecall p4lua53_dothecall
#define f_call p4lua53_f_call
#define global_State p4lua53_global_State
#define l_alloc p4lua53_l_alloc
#define l_mem p4lua53_l_mem
#define luaC_newobj p4lua53_luaC_newobj
#define luaC_step p4lua53_luaC_step
#define luaD_GCTM p4lua53_GCTM
#define luaD_call p4lua53_luaD_call
#define luaD_callnoyield p4lua53_luaD_callnoyield
#define luaD_growstack p4lua53_luaD_growstack
#define luaD_pcall p4lua53_pcall
#define luaD_precall p4lua53_luaD_precall
#define luaD_rawrunprotected p4lua53_rawrunprotected
#define luaE_setdebt p4lua53_luaE_setdebt
#define luaF_getlocalname p4lua53_luaF_getlocalname
#define luaH_get p4lua53_luaH_get
#define luaH_getn p4lua53_luaH_getn
#define luaH_getshortstr p4lua53_luaH_getshortstr
#define luaH_getstr p4lua53_luaH_getstr
#define luaL_Buffer  p4lua53_luaL_Buffer 
#define luaL_Reg  p4lua53_luaL_Reg 
#define luaL_Stream  p4lua53_luaL_Stream 
#define luaL_addlstring p4lua53_luaL_addlstring
#define luaL_addstring p4lua53_luaL_addstring
#define luaL_addvalue p4lua53_luaL_addvalue
#define luaL_argerror p4lua53_luaL_argerror
#define luaL_buffinit p4lua53_luaL_buffinit
#define luaL_buffinitsize p4lua53_luaL_buffinitsize
#define luaL_callmeta p4lua53_luaL_callmeta
#define luaL_checkany p4lua53_luaL_checkany
#define luaL_checkinteger p4lua53_luaL_checkinteger
#define luaL_checklstring p4lua53_luaL_checklstring
#define luaL_checknumber p4lua53_luaL_checknumber
#define luaL_checkoption p4lua53_luaL_checkoption
#define luaL_checkstack p4lua53_luaL_checkstack
#define luaL_checktype p4lua53_luaL_checktype
#define luaL_checkudata p4lua53_luaL_checkudata
#define luaL_checkversion_ p4lua53_luaL_checkversion_
#define luaL_error p4lua53_luaL_error
#define luaL_execresult p4lua53_luaL_execresult
#define luaL_fileresult p4lua53_luaL_fileresult
#define luaL_findtable p4lua53_luaL_findtable
#define luaL_getmetafield p4lua53_luaL_getmetafield
#define luaL_getsubtable p4lua53_luaL_getsubtable
#define luaL_gsub p4lua53_luaL_gsub
#define luaL_len p4lua53_luaL_len
#define luaL_loadbufferx p4lua53_luaL_loadbufferx
#define luaL_loadfilex p4lua53_luaL_loadfilex
#define luaL_loadstring p4lua53_luaL_loadstring
#define luaL_newmetatable p4lua53_luaL_newmetatable
#define luaL_newstate p4lua53_luaL_newstate
#define luaL_openlib p4lua53_luaL_openlib
#define luaL_openlibs p4lua53_luaL_openlibs
#define luaL_optinteger p4lua53_luaL_optinteger
#define luaL_optlstring p4lua53_luaL_optlstring
#define luaL_optnumber p4lua53_luaL_optnumber
#define luaL_prepbuffsize p4lua53_luaL_prepbuffsize
#define luaL_pushresult p4lua53_luaL_pushresult
#define luaL_pushresultsize p4lua53_luaL_pushresultsize
#define luaL_ref p4lua53_luaL_ref
#define luaL_register p4lua53_luaL_register
#define luaL_requiref p4lua53_luaL_requiref
#define luaL_setfuncs p4lua53_luaL_setfuncs
#define luaL_setmetatable p4lua53_luaL_setmetatable
#define luaL_testudata p4lua53_luaL_testudata
#define luaL_tolstring p4lua53_luaL_tolstring
#define luaL_traceback p4lua53_luaL_traceback
#define luaL_typerror p4lua53_luaL_typerror
#define luaL_unref p4lua53_luaL_unref
#define luaL_where p4lua53_luaL_where
#define luaM_realloc p4lua53_luaM_realloc
#define luaO_ceillog2 p4lua53_luaO_ceillog2
#define luaO_chunkid p4lua53_luaO_chunkid
#define luaO_fb2int p4lua53_luaO_fb2int
#define luaO_hexavalue p4lua53_luaO_hexavalue
#define luaO_int2fb p4lua53_luaO_int2fb
#define luaO_nilobject_ p4lua53_luaO_nilobject_
#define luaO_str2num p4lua53_luaO_str2num
#define luaO_utf8esc p4lua53_luaO_utf8esc
#define luaS_clearcache p4lua53_luaS_clearcache
#define luaS_eqlngstr p4lua53_luaS_eqlngstr
#define luaS_hash p4lua53_luaS_hash
#define luaS_hashlongstr p4lua53_luaS_hashlongstr
#define luaS_newudata p4lua53_luaS_newudata
#define luaT_gettm p4lua53_luaT_gettm
#define luaT_typenames_ p4lua53_luaT_typenames_
#define luaV_execute p4lua53_luaV_execute
#define luaZ_fill p4lua53_luaZ_fill
#define luaZ_read p4lua53_luaZ_read
#define lua_Alloc p4lua53_lua_Alloc
#define lua_CFunction p4lua53_lua_CFunction
#define lua_Debug p4lua53_lua_Debug
#define lua_Hook p4lua53_lua_Hook
#define lua_Integer p4lua53_lua_Integer
#define lua_KContext p4lua53_lua_KContext
#define lua_KFunction p4lua53_lua_KFunction
#define lua_Number p4lua53_lua_Number
#define lua_Reader p4lua53_lua_Reader
#define lua_State p4lua53_lua_State
#define lua_State p4lua53_lua_State
#define lua_TValue p4lua53_lua_TValue
#define lua_Unsigned p4lua53_lua_Unsigned
#define lua_Writer p4lua53_lua_Writer
#define lua_absindex p4lua53_lua_absindex
#define lua_arith p4lua53_lua_arith
#define lua_atpanic p4lua53_lua_atpanic
#define lua_callk p4lua53_lua_callk
#define lua_checkstack p4lua53_lua_checkstack
#define lua_close p4lua53_lua_close
#define lua_compare p4lua53_lua_compare
#define lua_concat p4lua53_lua_concat
#define lua_copy p4lua53_lua_copy
#define lua_cpcall p4lua53_lua_cpcall
#define lua_createtable p4lua53_lua_createtable
#define lua_dump p4lua53_lua_dump
#define lua_equal p4lua53_lua_equal
#define lua_error p4lua53_lua_error
#define lua_gc p4lua53_lua_gc
#define lua_getallocf p4lua53_lua_getallocf
#define lua_getfenv p4lua53_lua_getfenv
#define lua_getfield p4lua53_lua_getfield
#define lua_getglobal p4lua53_lua_getglobal
#define lua_gethook p4lua53_lua_gethook
#define lua_gethookcount p4lua53_lua_gethookcount
#define lua_gethookmask p4lua53_lua_gethookmask
#define lua_geti p4lua53_lua_geti
#define lua_getinfo p4lua53_lua_getinfo
#define lua_getlocal p4lua53_lua_getlocal
#define lua_getmetatable p4lua53_lua_getmetatable
#define lua_getstack p4lua53_lua_getstack
#define lua_gettable p4lua53_lua_gettable
#define lua_gettop p4lua53_lua_gettop
#define lua_getupvalue p4lua53_lua_getupvalue
#define lua_getuservalue p4lua53_lua_getuservalue
#define lua_ident p4lua53_lua_ident
#define lua_iscfunction p4lua53_lua_iscfunction
#define lua_isinteger p4lua53_lua_isinteger
#define lua_isnumber p4lua53_lua_isnumber
#define lua_isstring p4lua53_lua_isstring
#define lua_isuserdata p4lua53_lua_isuserdata
#define lua_isyieldable p4lua53_lua_isyieldable
#define lua_len p4lua53_lua_len
#define lua_lessthan p4lua53_lua_lessthan
#define lua_load p4lua53_lua_load
#define lua_longjmp p4lua53_lua_longjmp
#define lua_newstate p4lua53_lua_newstate
#define lua_newthread p4lua53_lua_newthread
#define lua_newuserdata p4lua53_lua_newuserdata
#define lua_next p4lua53_lua_next
#define lua_objlen p4lua53_lua_objlen
#define lua_pcallk p4lua53_lua_pcallk
#define lua_pushboolean p4lua53_lua_pushboolean
#define lua_pushcclosure p4lua53_lua_pushcclosure
#define lua_pushfstring p4lua53_lua_pushfstring
#define lua_pushinteger p4lua53_lua_pushinteger
#define lua_pushlightuserdata p4lua53_lua_pushlightuserdata
#define lua_pushlstring p4lua53_lua_pushlstring
#define lua_pushnil p4lua53_lua_pushnil
#define lua_pushnumber p4lua53_lua_pushnumber
#define lua_pushstring p4lua53_lua_pushstring
#define lua_pushthread p4lua53_lua_pushthread
#define lua_pushvalue p4lua53_lua_pushvalue
#define lua_pushvfstring p4lua53_lua_pushvfstring
#define lua_rawequal p4lua53_lua_rawequal
#define lua_rawget p4lua53_lua_rawget
#define lua_rawgeti p4lua53_lua_rawgeti
#define lua_rawgetp p4lua53_lua_rawgetp
#define lua_rawlen p4lua53_lua_rawlen
#define lua_rawset p4lua53_lua_rawset
#define lua_rawseti p4lua53_lua_rawseti
#define lua_rawsetp p4lua53_lua_rawsetp
#define lua_resume p4lua53_lua_resume
#define lua_rotate p4lua53_lua_rotate
#define lua_setallocf p4lua53_lua_setallocf
#define lua_setfenv p4lua53_lua_setfenv
#define lua_setfield p4lua53_lua_setfield
#define lua_setglobal p4lua53_lua_setglobal
#define lua_sethook p4lua53_lua_sethook
#define lua_seti p4lua53_lua_seti
#define lua_setlevel p4lua53_lua_setlevel
#define lua_setlocal p4lua53_lua_setlocal
#define lua_setmetatable p4lua53_lua_setmetatable
#define lua_settable p4lua53_lua_settable
#define lua_settop p4lua53_lua_settop
#define lua_setupvalue p4lua53_lua_setupvalue
#define lua_setuservalue p4lua53_lua_setuservalue
#define lua_status p4lua53_lua_status
#define lua_stringtonumber p4lua53_lua_stringtonumber
#define lua_toboolean p4lua53_lua_toboolean
#define lua_tocfunction p4lua53_lua_tocfunction
#define lua_tointegerx p4lua53_lua_tointegerx
#define lua_tolstring p4lua53_lua_tolstring
#define lua_tonumberx p4lua53_lua_tonumberx
#define lua_topointer p4lua53_lua_topointer
#define lua_tothread p4lua53_lua_tothread
#define lua_touserdata p4lua53_lua_touserdata
#define lua_type p4lua53_lua_type
#define lua_typename p4lua53_lua_typename
#define lua_upvalueid p4lua53_lua_upvalueid
#define lua_upvaluejoin p4lua53_lua_upvaluejoin
#define lua_version p4lua53_lua_version
#define lua_xmove p4lua53_lua_xmove
#define lua_yieldk p4lua53_lua_yieldk
#define luaopen_base p4lua53_luaopen_base
#define luaopen_bit32 p4lua53_luaopen_bit32
#define luaopen_coroutine p4lua53_luaopen_coroutine
#define luaopen_debug p4lua53_luaopen_debug
#define luaopen_io p4lua53_luaopen_io
#define luaopen_math p4lua53_luaopen_math
#define luaopen_os p4lua53_luaopen_os
#define luaopen_package p4lua53_luaopen_package
#define luaopen_string p4lua53_luaopen_string
#define luaopen_table p4lua53_luaopen_table
#define luaopen_utf8 p4lua53_luaopen_utf8
#define runafewfinalizers p4lua53_runafewfinalizers

# endif
